M48
; DRILL file KiCad 10.0.1-1-gbb48a3fe96 date 2026-08-11T15:11:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T15:11:14+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-1-gbb48a3fe96
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X105.472Y-56.675
X105.472Y-62.675
T2
X104.0Y-42.0
X104.0Y-105.0
X163.5Y-42.0
X163.5Y-105.0
M30
