M48
; DRILL file KiCad 10.0.1 date 2026-10-02T11:20:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-02T11:20:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X200.755Y-47.9
X200.755Y-53.9
T2
X197.25Y-41.25
X197.25Y-101.25
X272.25Y-101.25
X273.0Y-41.75
M30
