M48
; DRILL file KiCad 10.0.1 date 2026-05-17T11:52:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-17T11:52:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X105.5Y-54.34
X105.5Y-60.34
T2
X104.0Y-42.0
X104.0Y-105.0
X163.5Y-42.0
X163.5Y-105.0
M30
