#!/usr/bin/env bash
# Generate homeassistant/.env (gitignored, docker-compose only) from the one
# boat secrets file (homeassistant/secrets.yaml — see .ai_context/secrets.md).
# Docker Compose can't read HA's `!secret` YAML tag, so this is the bridge:
# secrets.yaml stays the single source of truth, .env is a regenerated
# artifact, never hand-edited. Re-run any time secrets.yaml's Influx/Grafana/
# Sisu Nav harvest (#80) values change.
#
# Usage: ./scripts/gen-docker-env.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$REPO_ROOT/homeassistant/secrets.yaml"
OUT="$REPO_ROOT/homeassistant/.env"

[[ -f "$SECRETS" ]] || { echo "missing $SECRETS" >&2; exit 1; }

read_secret() {
  awk -F': *' -v k="$1" '$1==k {gsub(/["'\'']/, "", $2); print $2; exit}' "$SECRETS"
}

{
  echo "# Generated by scripts/gen-docker-env.sh from homeassistant/secrets.yaml — do not hand-edit."
  echo "INFLUXDB_ORG=$(read_secret influxdb_org)"
  echo "INFLUXDB_BUCKET=$(read_secret influxdb_bucket)"
  echo "INFLUXDB_TOKEN=$(read_secret InfluxDB)"
  echo "INFLUXDB_ADMIN_USER=$(read_secret InfluxDBUser)"
  echo "INFLUXDB_ADMIN_PASSWORD=$(read_secret InfluxDBPwd)"
  echo "GRAFANA_ADMIN_USER=$(read_secret GrafanaUser)"
  echo "GRAFANA_ADMIN_PASSWORD=$(read_secret GrafanaPwd)"
  # Sisu Nav dated tile harvest (#80) — optional; empty/CHANGE_ME leaves the
  # matching provider refusing to run (sisu-nav/api/harvest/providers.mjs).
  echo "MAPTILER_API_KEY=$(read_secret maptiler_api_key)"
  echo "MAXAR_API_KEY=$(read_secret maxar_api_key)"
  echo "PLANET_API_KEY=$(read_secret planet_api_key)"
  echo "MAPBOX_ACCESS_TOKEN=$(read_secret mapbox_access_token)"
  echo "AISSTREAM_API_KEY=$(read_secret aisstream_api_key)"
} > "$OUT"

chmod 600 "$OUT"
echo "wrote $OUT"
