/**
 * Harvest keys live in the boat secrets file, not a second store (#102).
 * UI writes `homeassistant/secrets.yaml`, regenerates `homeassistant/.env`
 * (same mapping as scripts/gen-docker-env.sh), and updates process.env so
 * the running container does not need a compose recreate. .env is compose
 * injection at start — it is not baked into the image.
 */
import fs from 'node:fs';
import { loadProviders } from './providers.mjs';

const YAML_PATH = process.env.SISU_SECRETS_YAML || '';
const ENV_PATH = process.env.SISU_SECRETS_ENV || '';

/** Mirrors scripts/gen-docker-env.sh — keep in lockstep when adding keys. */
const ENV_FROM_YAML = [
  ['INFLUXDB_ORG', 'influxdb_org'],
  ['INFLUXDB_BUCKET', 'influxdb_bucket'],
  ['INFLUXDB_TOKEN', 'InfluxDB'],
  ['INFLUXDB_ADMIN_USER', 'InfluxDBUser'],
  ['INFLUXDB_ADMIN_PASSWORD', 'InfluxDBPwd'],
  ['GRAFANA_ADMIN_USER', 'GrafanaUser'],
  ['GRAFANA_ADMIN_PASSWORD', 'GrafanaPwd'],
  ['MAPTILER_API_KEY', 'maptiler_api_key'],
  ['MAXAR_API_KEY', 'maxar_api_key'],
  ['PLANET_API_KEY', 'planet_api_key'],
  ['MAPBOX_ACCESS_TOKEN', 'mapbox_access_token'],
  ['GOOGLE_MAPS_API_KEY', 'google_maps_api_key'],
  ['AZURE_MAPS_SUBSCRIPTION_KEY', 'azure_maps_subscription_key'],
  ['AISSTREAM_API_KEY', 'aisstream_api_key'],
];

function httpError(status, message) {
  const err = new Error(message);
  err.status = status;
  return err;
}

export function yamlKeyForEnv(secretEnv) {
  return String(secretEnv || '')
    .trim()
    .toLowerCase();
}

export function allowedSecretEnvs() {
  const out = new Set();
  for (const p of Object.values(loadProviders())) {
    if (p.access === 'secret' && p.secretEnv) out.add(p.secretEnv);
  }
  return out;
}

function readFile(path) {
  return fs.readFileSync(path, 'utf8');
}

function readYamlValue(text, key) {
  const re = new RegExp(`^${key}:\\s*(.*)$`, 'm');
  const m = text.match(re);
  if (!m) return '';
  return m[1].trim().replace(/^["']|["']$/g, '');
}

function upsertYamlKey(text, key, value) {
  const line = `${key}: ${JSON.stringify(value)}`;
  const re = new RegExp(`^${key}:.*$`, 'm');
  if (re.test(text)) return text.replace(re, line);
  return `${text.replace(/\s*$/, '')}\n${line}\n`;
}

function writeMode(path, text, mode) {
  fs.writeFileSync(path, text, { encoding: 'utf8', mode });
  try {
    fs.chmodSync(path, mode);
  } catch {
    /* bind-mount chmod can no-op; write is what matters */
  }
}

function regenEnv(yamlText) {
  if (!ENV_PATH) return;
  const lines = ['# Generated by sisu-nav-api from secrets.yaml — do not hand-edit.'];
  for (const [envName, yamlKey] of ENV_FROM_YAML) {
    lines.push(`${envName}=${readYamlValue(yamlText, yamlKey)}`);
  }
  writeMode(ENV_PATH, `${lines.join('\n')}\n`, 0o600);
}

export function secretsMounted() {
  return Boolean(YAML_PATH && fs.existsSync(YAML_PATH));
}

/** Boot: secrets.yaml is source of truth for harvest keys when the file is mounted. */
export function applyBoatSecrets() {
  if (!secretsMounted()) return { applied: 0 };
  const text = readFile(YAML_PATH);
  let applied = 0;
  for (const envName of allowedSecretEnvs()) {
    const val = readYamlValue(text, yamlKeyForEnv(envName));
    if (!val) continue;
    process.env[envName] = val;
    applied += 1;
  }
  return { applied };
}

export function saveHarvestSecret(secretEnv, value) {
  const envName = String(secretEnv || '').trim();
  if (!allowedSecretEnvs().has(envName)) {
    throw httpError(400, `unknown harvest secret ${envName}`);
  }
  const raw = String(value ?? '').trim();
  if (!raw || raw === 'CHANGE_ME') {
    throw httpError(400, 'empty or CHANGE_ME key refused');
  }
  if (!secretsMounted()) {
    throw httpError(503, 'boat secrets.yaml is not mounted in this container');
  }
  const yamlKey = yamlKeyForEnv(envName);
  const next = upsertYamlKey(readFile(YAML_PATH), yamlKey, raw);
  writeMode(YAML_PATH, next, 0o600);
  regenEnv(next);
  process.env[envName] = raw;
  return { secretEnv: envName, configured: true };
}

export function clearHarvestSecret(secretEnv) {
  const envName = String(secretEnv || '').trim();
  if (!allowedSecretEnvs().has(envName)) {
    throw httpError(400, `unknown harvest secret ${envName}`);
  }
  if (!secretsMounted()) {
    throw httpError(503, 'boat secrets.yaml is not mounted in this container');
  }
  const yamlKey = yamlKeyForEnv(envName);
  const next = upsertYamlKey(readFile(YAML_PATH), yamlKey, 'CHANGE_ME');
  writeMode(YAML_PATH, next, 0o600);
  regenEnv(next);
  process.env[envName] = 'CHANGE_ME';
  return { secretEnv: envName, configured: false };
}
